### ISSUE TITLE
Find a temporary solution to the snyk.io / requirements.txt / setup tools issue.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/pulse#101]
They don't seem to be able to process the setup.py / requirements.txt redirection. If we can sort this out in the meantime, that'd be great. hacks accepted (duplicate requirements)

We'll need some component scanning before launch.

**Comment by buckley-w-david** [comment]
Can I be added to our snyk.io account so that I can test solutions and see their compatibility with snyk?

**Comment by buckley-w-david** [comment]
#136 should address this issue

**Comment by buckley-w-david** [comment]
Snyk dependency scanning fix has been merged in, closing issue
