### ISSUE TITLE
Domain Scan lambda function AWS configuration

### ISSUE THREAD

**Issue by buckley-w-david** [cds-snc/pulse#15]
As per https://github.com/18F/domain-scan/blob/master/docs/lambda.md there are two things we need to do to get the lambda scanners deployed.

1. "Configure aws to have permission to write to Lambda and to read from CloudWatch. This usually means AWS API credentials, but if you're running this inside of an AWS service like EC2, you can use IAM roles to automatically grant permissions."

This means we'll need to generate the credentials (I cannot)

2. "Define an IAM role in your AWS account that gives the Lambda functions themselves necessary permissions to interact with basic AWS APIs (like CloudTrail for logging).
The simplest role to create is one based on a "AWSLambdaFullAccess" policy, which will give your Lambda functions everything they need."

This one is fairly simple, I just don't have the permissions to do it.

**Comment by szinck1** [comment]
Stealing this from @obrien-j.
Will complete setup in terraform, see https://github.com/cds-snc/aws-staging-live/tree/master/staging/services/pulse

**Comment by buckley-w-david** [comment]
Closing, we have docs for how to deploy the scanners
