### ISSUE TITLE
French department names

### ISSUE THREAD

**Issue by evadb** [cds-snc/pulse#33]
We will need to add the ability to store French department names. Also, the tables will need to be internationalized

**Comment by obrien-j** [comment]
https://open.canada.ca/data/en/dataset/c05e8a2b-4e8b-4da7-b6f3-33f4848d3c09

This should be useful but it appears like the csv link is english only. I'm pretty sure I know who populates that so should be able to get that sorted.

**Comment by obrien-j** [comment]
Looks like there was actually a bug in the open canada dataset. Got Stephen O'Neil from Infobase/EMS team to sort it out. Will link up the latest dataset here shortly.

**Comment by buckley-w-david** [comment]
@evadb This is done now, right?

**Comment by evadb** [comment]
It is! Thanks @buckley-w-david
