### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by buckley-w-david** [cds-snc/pulse#42]
Everything is called `pulse` here, we need to come up with our own name and rename everything.

---

Things needed to be rebranded  
- [x] repository name
- [x] README info
- [x] python package names
- [x] frontend interface

**Comment by buckley-w-david** [comment]
Only need to do repo rename now.

@obrien-j I know you were talking about this earlier, when can we go through with it?

**Comment by obrien-j** [comment]
Any time. Just give me the word. Do we want to split out tracker at the same time? It'd probably fix the snyk bug as well.

**Comment by pcraig3** [comment]
Can I suggest "Paulse"?

**Comment by buckley-w-david** [comment]
Repo has been split, and each one named use the correct name
https://github.com/cds-snc/tracker and https://github.com/cds-snc/track-web
