### ISSUE TITLE
Pagination beside search bar should be centred with bar 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#47]
The pagination next to the search bar should be centred in line with the rest of the text (moved down a little bit).

![image](https://user-images.githubusercontent.com/3474250/40269700-3e00ade2-5b50-11e8-929c-3c269c66c1f8.png)

@evadb @samsadasivan

**Comment by evadb** [comment]
Fixed: 

<img width="1221" alt="screen shot 2018-05-22 at 5 15 28 pm" src="https://user-images.githubusercontent.com/1545806/40439463-fe3b802e-5e88-11e8-91c0-cfe1e1e172ce.png">
