### ISSUE TITLE
Table is showing different column headers before it loads properly 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#52]
If the table doesn't load as expected, you see an `Agency` header.

Expected `Agency` wouldn't appear.

**Comment by sidewalkballet** [comment]
@buckley-w-david (I still can't assign... 😠)

**Comment by evadb** [comment]
This is more of a job for me

**Comment by evadb** [comment]
I'll look into it

**Comment by sidewalkballet** [comment]
ah, thanks @evadb

**Comment by buckley-w-david** [comment]
@evadb Not that I mind not having to do a thing, but isn't that more me? isn't it just the result of the csv route?

**Comment by evadb** [comment]
@buckley-w-david it's an issue that should be fixed once the table loads properly tbh

**Comment by buckley-w-david** [comment]
Ignore me, I commented on the wrong issue
