### ISSUE TITLE
Some domains are appearing twice in the table

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#53]
1. Go to the second page
2. Observe that domains from `humanrights.ca` onwards appear twice: 
![image](https://user-images.githubusercontent.com/3474250/40269767-9a094752-5b50-11e8-83df-1b50e9145a12.png)

Expected that the domains would only appear once. 

This happens on page 2 and 3, but not 1 or 4.

**Comment by buckley-w-david** [comment]
Probably an issue with the input data, but will investigate.

**Comment by buckley-w-david** [comment]
Unable to reproduce with current dataset. I believe this instance was simply due to bad input data. For now I believe this issue can be closed.
