### ISSUE TITLE
Accented characters are not displaying properly 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#55]
On the first page - ("By Organization"), observe `AÃ©roport de QuÃ©bec Inc.`: 
![image](https://user-images.githubusercontent.com/3474250/40269780-b26990a4-5b50-11e8-8dec-9076495e4733.png)

Expected `Aéroport de Québec`

**Comment by buckley-w-david** [comment]
Yeah, this one is a simple input data problem, when merging together input csvs there seems to have been some encoding mixups.

**Comment by buckley-w-david** [comment]
Confirmed that this was an issue with bad input data. New versions of the data no longer have this problem. 

![updated data](https://user-images.githubusercontent.com/1952571/40946058-a17bd91a-6829-11e8-93db-c3c07cc4d1d5.png)

Closing
