### ISSUE TITLE
Dashboard should be using the canada.ca favicon

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#56]
The dashboard favicon is Pulse's favicon. Use this asset instead: https://www.canada.ca/etc/designs/canada/wet-boew/assets/favicon.ico

**Comment by evadb** [comment]
<img width="146" alt="screen shot 2018-05-22 at 3 42 15 pm" src="https://user-images.githubusercontent.com/1545806/40386901-015698a8-5dd9-11e8-92fb-7ce4e1599fad.png">

Closing!
