### ISSUE TITLE
URL linked from data table needs to be updated from 18F

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#60]
1. Go to the dashboard, filter down to specific services.
2. Click on `publicly discoverable services` and observe it leads you to a 404, on a path from Pulse: 
![image](https://user-images.githubusercontent.com/3474250/40269792-d956ed56-5b50-11e8-8941-e7c2b66aabb1.png)

Expected that that URL would lead to `/guidance/#subdomains`, with no `/https` beforehand.

**Comment by evadb** [comment]
<img width="1133" alt="screen shot 2018-05-22 at 3 13 50 pm" src="https://user-images.githubusercontent.com/1545806/40386880-f25dc9ac-5dd8-11e8-9a75-6534e8fdab4d.png">

closing!
