### ISSUE TITLE
"Mail placeholder" should be zzTBSCybers@tbs-sct.gc.ca

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#61]
Change `mail placeholder` to `zzTBSCybers@tbs-sct.gc.ca`

![image](https://user-images.githubusercontent.com/3474250/40269802-00652958-5b51-11e8-8f3c-baec035fb43b.png)

**Comment by evadb** [comment]
<img width="1133" alt="screen shot 2018-05-22 at 3 13 50 pm" src="https://user-images.githubusercontent.com/1545806/40386846-dd784ef4-5dd8-11e8-9bb2-5bc884dc421e.png">

Closing!
