### ISSUE TITLE
Invalid scan results (no http/hsts, but values on rc4/3des column)

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/pulse#66]
![image](https://user-images.githubusercontent.com/17616596/40263177-b4c280be-5adc-11e8-95b5-9491c65a799e.png)

Might be a flaw in domain-scan and/or parsing algs. Noting for followup

**Comment by buckley-w-david** [comment]
The "No" for HTTPs doesn't mean it does not have it, just means it does not enforce it.

**Comment by obrien-j** [comment]
Hrmm... and so it is.  Makes sense I guess. I'll mark this as closed since it's operating as designed. We may want to revisit this from an additional measurement criteria.

**Comment by konklone** [comment]
Pulse used to have two columns, for `Uses HTTPS` and `Enforces HTTPS`. Eventually, it became clear to me that measuring only whether a service is using-but-not-enforcing HTTPS isn't very useful as an intermediate state. HTTPS can't be guaranteed to be there in a meaningful way unless it's enforced. Showing it can give implementers a false sense of meaningful progress in rolling HTTPS support out to a web service.
